name: either
description: A package that provides an Either type.
version: 1.0.0
homepage: https://github.com/felipeddev/either

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
